# Generated by Django 3.0.5 on 2020-04-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='copyright',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.TextField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='store.Publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='version',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='', help_text='Name of publisher', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='privacy_policy_url',
            field=models.URLField(default=1, help_text='Privacy policy link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='suppport_url',
            field=models.URLField(default='', help_text='Link to useful app resources'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(default='', help_text='Official website of app'),
            preserve_default=False,
        ),
    ]
