# Generated by Django 3.0.5 on 2020-04-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='categories',
            field=models.ManyToManyField(to='store.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', help_text='Category description', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', help_text='Category name', max_length=100),
            preserve_default=False,
        ),
    ]
